[versions]
spotbugs = "6.4.8"
sendgrid = "4.10.1"
jakartaMail = "2.1.5"
log4j = "2.23.0"
junit = "6.0.2"
disruptor = "4.0.0"
javaxMail = "1.6.2"
spotbugsPlugin = "4.9.8"
findsecbugs = "1.14.0"
jackson = "2.20.1"
commonsCodec = "1.21.0"
jreleaser = "1.21.0"

[libraries]
sendgrid-java = { module = "com.sendgrid:sendgrid-java", version.ref = "sendgrid" }
jakarta-mail-api = { module = "jakarta.mail:jakarta.mail-api", version.ref = "jakartaMail" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
disruptor = { module = "com.lmax:disruptor", version.ref = "disruptor" }
javax-mail = { module = "com.sun.mail:javax.mail", version.ref = "javaxMail" }
spotbugs-plugin = { module = "com.github.spotbugs:spotbugs", version.ref = "spotbugsPlugin" }
findsecbugs-plugin = { module = "com.h3xstream.findsecbugs:findsecbugs-plugin", version.ref = "findsecbugs" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commonsCodec" }

[plugins]
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
